import { Payment, getNFT, LocalChain, opentaskai } from 'opentaskai-web3-jssdk';
import { APP_ENV } from '../src/constants';
import { Wallet } from 'ethers';
console.log('app env:', APP_ENV);
export const signer = new Wallet(APP_ENV.SIGNER_PK);
export const chain = new LocalChain(APP_ENV.CHAIN_ID, APP_ENV.CHAIN_RPC);
export const payment = new Payment(chain);
payment.setSigner(signer);
const network = opentaskai.getNetworkMeta(chain.chainId);
export const aiOriginals = getNFT(chain, network.AIOriginals);
aiOriginals.setSigner(signer);
